PrimusFlex.Web/Areas/Employee/ViewModels/Reports/WorkReportViewModel.cs
namespace PrimusFlex.Web.Areas.Employee.ViewModels
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.Web.Mvc;

    using Data.Models;
    using Data.Models.Types;

    using Infrastructure.Mapping;
    using AutoMapper;

    public class WorkReportViewModel : IMapFrom<WorkReport>, IMapTo<WorkReport>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public int EmployeeId { get; set; }

        [Required]
        public DateTime Date { get; set; }

        public int WeekNumber { get; set; }

        [Required]
        [Display(Name = "Post Code")]
        public string PostCode { get; set; }

        [Required]
        public string Address { get; set; }

        [Display(Name = "Kitchcen")]
        public KitchenName KitchenName { get; set; }

        public string Plot { get; set; }

        [Display(Name = "Work Type")]
        public WorkType WorkType { get; set; }

        public decimal Price { get; set; }

        public string Note { get; set; }



        public void CreateMappings(IMapperConfiguration configuration)
        {
            configuration.CreateMap<WorkReport, WorkReportViewModel>()
                .ForMember(x => x.PostCode, opt => opt.MapFrom(x => x.ConstructionSite.PostCode));

            configuration.CreateMap<WorkReport, WorkReportViewModel>()
                .ForMember(x => x.Address, opt => opt.MapFrom(x => x.ConstructionSite.Address));
        }
    }
}

PrimusFlex.Web/Areas/Employee/Controllers/ReportsController.cs
namespace PrimusFlex.Web.Areas.Employee.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using Microsoft.AspNet.Identity;

    using Infrastructure.Mapping;
    using Infrastructure;
    using Web.Controllers;
    using ViewModels;
    using Models;
    using Data.Common;
    using Data.Models;
    using Infrastructure.Data.Helpers;
    [Authorize(Roles = "Employee")]
    public class ReportsController : BaseController
    {
        private readonly IDbRepository<WorkReport> workReports;
        private readonly IDbRepository<Employee> employees;
        private readonly IDbRepository<ConstructionSite> constructionSites;

        public ReportsController(IDbRepository<WorkReport> workReports,
            IDbRepository<Employee> employees,
            IDbRepository<ConstructionSite> constructionSites)
        {
            this.workReports = workReports;
            this.employees = employees;
            this.constructionSites = constructionSites;
        }

        // GET: Employee/Reports{/Index}
        public ActionResult Index()
        {
            var user = this.UserManager.FindById(this.User.Identity.GetUserId());

            var employee = this.employees.All()
                .First(e => e.UserId == user.Id);

            ViewBag.EmployeeName = employee.Name;

            var reports = this.workReports.All()
                .Where(wr => wr.EmployeeId == employee.Id)
                .OrderByDescending(wr => wr.WeekNumber)
                .ThenBy(wr => wr.Date)
                .To<WorkReportViewModel>()
                .ToList();

            ViewBag.WeekSummury = WeekSummury.MakeWeekSummury(reports);

            return View(reports);
        }

        // GET: Employee/Repoerts/CreateWithNewSite
        [HttpGet]
        public ActionResult CreateWithNewSite()
        {
            var user = this.UserManager.FindById(this.User.Identity.GetUserId());

            var employee = this.employees.All()
                .First(e => e.UserId == user.Id);

            var model = new WorkReportViewModel()
            {
                EmployeeId = employee.Id,
                Date = DateTime.Now
            };

            return this.View(model);
        }

        // GET: Employee/Reports/Create
        [HttpGet]
        public ActionResult Create()
        {
            var user = this.UserManager.FindById(this.User.Identity.GetUserId());

            var employee = this.employees.All()
                .First(e => e.UserId == user.Id);

            var model = new WorkReportViewModel()
            {
                EmployeeId = employee.Id,
                Date = DateTime.Now
            };

            ViewBag.PostCodes = ConstructionSites.SetDropDownListsFrom("PostCodes");
            ViewBag.Addresses = ConstructionSites.SetDropDownListsFrom("Addresses");

            return this.View(model);
        }

        // POST: Employee/Reports/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WorkReportViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            var report = this.Mapper.Map<WorkReport>(model);
            report.WeekNumber = DateTimeHelper.GetIso8601WeekOfYear(model.Date);
            
            int siteId = 0;
            if (!int.TryParse(model.PostCode, out siteId))
            {
                // Site not exist. Create new site.
                var constructionSite = new ConstructionSite()
                {
                    PostCode = model.PostCode,
                    Address = model.Address
                };
                this.constructionSites.Add(constructionSite);
                siteId = constructionSite.Id;
            }

            report.ConstructionSiteId = siteId;

            this.workReports.Add(report);
            this.workReports.Save();

            return RedirectToAction("Index");
        }

        // GET: Employee/Reports/Update/Id
        [HttpGet]
        public ActionResult Update(int id)
        {
            var report = this.workReports.GetById(id);

            var model = this.Mapper.Map<WorkReportViewModel>(report);

            var constructionSite = this.constructionSites.GetById(report.ConstructionSiteId);
            
            ViewBag.PostCodes = ConstructionSites.SetDropDownListsFrom("PostCodes", constructionSite.PostCode);
            ViewBag.Addresses = ConstructionSites.SetDropDownListsFrom("Addresses", constructionSite.Address);

            return this.View(model);
        }

        // GET: Employee/Reports/UpdateWithNewSite/Id
        [HttpGet]
        public ActionResult UpdateWithNewSite(int id)
        {
            var report = this.workReports.GetById(id);

            var model = this.Mapper.Map<WorkReportViewModel>(report);

            return this.View(model);
        }

        // POST: Employee/Reports/Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(WorkReportViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            var report = this.workReports.GetById(model.Id);
            report.Date = model.Date;
            report.KitchenName = model.KitchenName;
            report.Plot = model.Plot;
            report.WorkType = model.WorkType;
            report.Price = model.Price;
            report.Note = model.Note;
            report.WeekNumber = DateTimeHelper.GetIso8601WeekOfYear(model.Date);

            int siteId = 0;
            if (!int.TryParse(model.PostCode, out siteId))
            {
                // Site not exist. Create new site.
                var constructionSite = new ConstructionSite()
                {
                    PostCode = model.PostCode,
                    Address = model.Address
                };
                this.constructionSites.Add(constructionSite);
                siteId = constructionSite.Id;
            }

            report.ConstructionSiteId = siteId;

            this.workReports.Update(report);
            this.workReports.Save();

            return RedirectToAction("Index");
        }

        // TODO: Create Delete work report Action
    }
}

PrimusFlex.Web/Areas/Employee/Views/Reports/Create.cshtml
@model PrimusFlex.Web.Areas.Employee.ViewModels.WorkReportViewModel

@{
    ViewBag.Title = "Create";
}

<div class="nav-path">
    <a href="@Url.Content("~/Employee/Reports")">Reports</a> / Create a new report
</div>

@using (Html.BeginForm("Create", "Reports", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.EmployeeId)

    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Date)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PostCode, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PostCode, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.KitchenName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.KitchenName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Plot, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Plot, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.WorkType, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.WorkType, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Price, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Note, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Note, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
            <a href="@Url.Content("~/Employee/Reports")" class="btn btn-default">Cancel</a>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $("#datepicker").datepicker({ maxDate: new Date() });
        });
    </script>
}

PrimusFlex.Web/Areas/Employee/Views/Reports/CreateWithNewSite.cshtml
@model PrimusFlex.Web.Areas.Employee.ViewModels.WorkReportViewModel

@{
    ViewBag.Title = "Create";
}

<div class="nav-path">
    <a href="@Url.Content("~/Employee/Reports")">Reports</a> / Create a new report
</div>

@using (Html.BeginForm("Create", "Reports", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.EmployeeId)

    <div class="form-group required">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Date)
        </div>
    </div>

    <hr />
    <div class="col-md-offset-2 col-md-10">
        <strong>Site details</strong>
        <a href="@Url.Content("~/Employee/Reports/Create")" class="btn btn-default btn-xs pull-right"><i class="fa fa-search"></i> Select from existing sites</a>
    </div>
    <div class="form-group required">
        @Html.LabelFor(m => m.PostCode, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PostCode, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PostCode, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group required">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
        </div>
    </div>
    <hr />

    <div class="form-group">
        @Html.LabelFor(m => m.KitchenName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.KitchenName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Plot, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Plot, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.WorkType, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.WorkType, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Price, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Note, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Note, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
            <a href="@Url.Content("~/Employee/Reports")" class="btn btn-default">Cancel</a>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $("#datepicker").datepicker({ maxDate: new Date() });
        });
    </script>
}

PrimusFlex.Web/Areas/Employee/Views/Reports/Index.cshtml
@using PrimusFlex.Web.Areas.Employee.ViewModels
@using PrimusFlex.Web.Areas.Employee.Models

@model IEnumerable<WorkReportViewModel>

@{
    ViewBag.Title = "Reports";
    var WeekSummary = (Dictionary<int, WeekSummury>)ViewBag.WeekSummury;
}

<div class="nav-path">
    @ViewBag.EmployeeName / Work reports
    <div class="pull-right">
        <a href="@Url.Content("~/Employee/Reports/Create/")" class="btn btn-default btn-sm"><i class="fa fa-file-text"></i> New report</a>
    </div>
</div>

@if (Model.Count() > 0)
{
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>Date</th>
                <th>Post Code</th>
                <th>Address</th>
                <th>Kitchen</th>
                <th>Plot</th>
                <th>Work Type</th>
                <th>Price</th>
                <th>Note</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            @{
                int currentWeekNumber = -1;
            }

            @foreach (var report in Model)
            {
                if (currentWeekNumber != report.WeekNumber)
                {
                    currentWeekNumber = report.WeekNumber;
                    <tr class="week-limiter">
                        <td colspan="6">
                            Week @currentWeekNumber
                        </td>
                        <td colspan="3">
                            @WeekSummary[currentWeekNumber].TotalPrice
                            /<span>@WeekSummary[currentWeekNumber].TotalPriceLess20prc</span>
                        </td>
                    </tr>
                }

                <tr>
                    <td>@report.Date.ToString("dd/MM/yyyy, ddd")</td>
                    <td>@report.PostCode</td>
                    <td>@report.Address</td>
                    <td>@report.KitchenName</td>
                    <td>@report.Plot</td>
                    <td>@report.WorkType</td>
                    <td>@report.Price</td>
                    <td>@report.Note</td>
                    <td>
                        <a href="@Url.Content("~/Employee/Reports/Update/" + report.Id)" title="Edit" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></a>
                        <a href="@Url.Content("~/Employee/Reports/Delete/" + report.Id)" data-toggle="confirmation" title="Delete" class="btn btn-default btn-xs"><i class="fa fa-remove"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div id="dialog-confirm" title="Confirmation Required">
        <p>
            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
            This report will be deleted. Are you sure?
        </p>
    </div>
                }

@section scripts{
    <script>
        $("document").ready(function () {
            $("#dialog-confirm").dialog({
                resizable: false,
                height: 200,
                autoOpen: false,
                modal: true,
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });
        });

        $("[data-toggle='confirmation']").click(function (e) {
            e.preventDefault();
            var targetUrl = $(this).attr("href");

            $("#dialog-confirm").dialog({
                buttons: {
                    "Confirm": function () {
                        window.location.href = targetUrl;
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });

            $("#dialog-confirm").dialog("open");
        });
    </script>
}

PrimusFlex.Web/Areas/Employee/Views/Reports/Update.cshtml
@model PrimusFlex.Web.Areas.Employee.ViewModels.WorkReportViewModel

@{
    ViewBag.Title = "Update";
}

<div class="nav-path">
    <a href="@Url.Content("~/Employee/Reports")">Reports</a> / Update (Report: @Model.Date.ToShortDateString())
</div>

@using (Html.BeginForm("Update", "Reports", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.EmployeeId)

    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Date)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PostCode, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PostCode, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.KitchenName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.KitchenName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Plot, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Plot, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.WorkType, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.WorkType, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Price, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Note, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Note, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Update" />
            <a href="@Url.Content("~/Employee/Reports")" class="btn btn-default">Cancel</a>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $("#datepicker").datepicker({ maxDate: new Date() });
        });
    </script>
}

PrimusFlex.Web/Areas/Employee/Views/Reports/UpdateWithNewSite.cshtml
@model PrimusFlex.Web.Areas.Employee.ViewModels.WorkReportViewModel

@{
    ViewBag.Title = "Update";
}

<div class="nav-path">
    <a href="@Url.Content("~/Employee/Reports")">Reports</a> / Update (Report: @Model.Date.ToShortDateString())
</div>

@using (Html.BeginForm("Update", "Reports", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.EmployeeId)

    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Date)
        </div>
    </div>

    <hr />
    <div class="col-md-offset-2 col-md-10">
        <strong>Site details</strong>
        <a href="@Url.Content("~/Employee/Reports/Update/" + Model.Id)" class="btn btn-default btn-xs pull-right"><i class="fa fa-search"></i> Select from existing sites</a>
    </div>
    <div class="form-group required">
        @Html.LabelFor(m => m.PostCode, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PostCode, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PostCode, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group required">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
        </div>
    </div>
    <hr />

    <div class="form-group">
        @Html.LabelFor(m => m.KitchenName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.KitchenName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Plot, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Plot, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.WorkType, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.WorkType, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Price, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Note, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Note, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Update" />
            <a href="@Url.Content("~/Employee/Reports")" class="btn btn-default">Cancel</a>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $("#datepicker").datepicker({ maxDate: new Date() });
        });
    </script>
}